env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
globals:
  React: true
  ReactDOM: true
  p5: true
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  'react/prop-types': 'off',
  'import/no-absolute-path': 'off'
}
